# Generated by Django 4.2.11 on 2025-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_orderline_size_order_student_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='measurements',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(blank=True, help_text='Standard sizes available (S, M, L, XL, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
