# Generated by Django 4.2.11 on 2025-09-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tailorprofile_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='payment_details',
            field=models.TextField(blank=True, help_text='Bank account details', null=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
