# Generated by Django 4.2.11 on 2025-09-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deliverypartnerprofile_email_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='student_age',
            field=models.PositiveIntegerField(blank=True, help_text='Age in years', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='student_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='student_grade',
            field=models.CharField(blank=True, help_text='Grade/Class', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='student_height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='measurements',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='garment_type',
            field=models.CharField(blank=True, choices=[('shirt_blouse', 'Shirt/Blouse (formal)'), ('polo_tshirt', 'Polo/T-shirt'), ('trousers_pants', 'Trousers/Pants'), ('skirt', 'Skirt'), ('shorts', 'Shorts'), ('pinafore', 'Pinafore/Overall/Tunic/Dress'), ('blazer', 'Blazer/Jacket/Cardigan'), ('pe_kit', 'PE Kit'), ('accessory', 'Accessory (Tie/Belt)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list, help_text='Standard sizes available (S, M, L, XL, etc.)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
