# Generated by Django 4.2.11 on 2025-09-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_name_alter_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('paypal', 'PayPal')], default='paypal', max_length=50),
        ),
    ]
