# Generated by Django 4.2.11 on 2025-09-11 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderline',
            name='student_age',
            field=models.PositiveIntegerField(blank=True, help_text='Age in years', null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='student_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='student_grade',
            field=models.CharField(blank=True, help_text='Grade/Class', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='student_height',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_age', models.PositiveIntegerField(blank=True, help_text='Age in years', null=True)),
                ('student_grade', models.CharField(blank=True, help_text='Grade/Class', max_length=50, null=True)),
                ('student_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('student_height', models.DecimalField(blank=True, decimal_places=1, help_text='Height in cm', max_digits=5, null=True)),
                ('measurements', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
