# Generated by Django 4.2.11 on 2025-09-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cart_orderline_student_age_orderline_student_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='measurements',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='measurements',
        ),
    ]
