# Generated by Django 4.2.11 on 2025-09-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cartitem_measurements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='measurements',
            field=models.JSONField(blank=True, help_text='Body measurements in cm', null=True),
        ),
    ]
